pub(crate) enum Instruction {
	NOP,
	STOP,
	HALT,
	PUSH(StackTarget),
	POP(StackTarget),
	ADD(ArithmeticTarget),
	ADD16(Reg16Target),
	ADDC(ArithmeticTarget),
	ADDSP,
	SUB(ArithmeticTarget),
	SUB16(Reg16Target),
	SUBC(ArithmeticTarget),
	AND(ArithmeticTarget),
	OR(ArithmeticTarget),
	XOR(ArithmeticTarget),
	CMP(ArithmeticTarget),
	INC(ArithmeticTarget),
	INC16(Reg16Target),
	DEC(ArithmeticTarget),
	DEC16(Reg16Target),
	CCF,
	SCF,
	RRA,
	RLA,
	RRCA,
	RLCA,
	CPL,
	BIT(u8, ArithmeticTarget),
	RESET(u8, ArithmeticTarget),
	SET(u8, ArithmeticTarget),
	SRL(ArithmeticTarget),
	RR(ArithmeticTarget),
	RL(ArithmeticTarget),
	RRC(ArithmeticTarget),
	RLC(ArithmeticTarget),
	SRA(ArithmeticTarget),
	SLA(ArithmeticTarget),
	SWAP(ArithmeticTarget),
	DAA,
	JP(JumpTest),
	JR(JumpTest),
	LD(LoadType),
	CALL(JumpTest),
	RET(JumpTest),
	RETI,
	EI,
	DI,
	RST(u8),
}
impl Instruction {
	pub(crate) fn from_byte(byte: u8, prefixed: bool) -> Option<Instruction> {
		if prefixed {
			Instruction::from_byte_prefixed(byte)
		} else {
			Instruction::from_byte_not_prefixed(byte)
		}
	}
	fn from_byte_prefixed(byte: u8) -> Option<Instruction> {
		match byte {
			// RLC
			0x00 => Some(Instruction::RLC(ArithmeticTarget::B)),
			0x01 => Some(Instruction::RLC(ArithmeticTarget::C)),
			0x02 => Some(Instruction::RLC(ArithmeticTarget::D)),
			0x03 => Some(Instruction::RLC(ArithmeticTarget::E)),
			0x04 => Some(Instruction::RLC(ArithmeticTarget::H)),
			0x05 => Some(Instruction::RLC(ArithmeticTarget::L)),
			0x06 => Some(Instruction::RLC(ArithmeticTarget::HL)),
			0x07 => Some(Instruction::RLC(ArithmeticTarget::A)),
			// RRC
			0x08 => Some(Instruction::RRC(ArithmeticTarget::B)),
			0x09 => Some(Instruction::RRC(ArithmeticTarget::C)),
			0x0A => Some(Instruction::RRC(ArithmeticTarget::D)),
			0x0B => Some(Instruction::RRC(ArithmeticTarget::E)),
			0x0C => Some(Instruction::RRC(ArithmeticTarget::H)),
			0x0D => Some(Instruction::RRC(ArithmeticTarget::L)),
			0x0E => Some(Instruction::RRC(ArithmeticTarget::HL)),
			0x0F => Some(Instruction::RRC(ArithmeticTarget::A)),
			// RL
			0x10 => Some(Instruction::RL(ArithmeticTarget::B)),
			0x11 => Some(Instruction::RL(ArithmeticTarget::C)),
			0x12 => Some(Instruction::RL(ArithmeticTarget::D)),
			0x13 => Some(Instruction::RL(ArithmeticTarget::E)),
			0x14 => Some(Instruction::RL(ArithmeticTarget::H)),
			0x15 => Some(Instruction::RL(ArithmeticTarget::L)),
			0x16 => Some(Instruction::RL(ArithmeticTarget::HL)),
			0x17 => Some(Instruction::RL(ArithmeticTarget::A)),
			// RR
			0x18 => Some(Instruction::RR(ArithmeticTarget::B)),
			0x19 => Some(Instruction::RR(ArithmeticTarget::C)),
			0x1A => Some(Instruction::RR(ArithmeticTarget::D)),
			0x1B => Some(Instruction::RR(ArithmeticTarget::E)),
			0x1C => Some(Instruction::RR(ArithmeticTarget::H)),
			0x1D => Some(Instruction::RR(ArithmeticTarget::L)),
			0x1E => Some(Instruction::RR(ArithmeticTarget::HL)),
			0x1F => Some(Instruction::RR(ArithmeticTarget::A)),
			// SLA
			0x20 => Some(Instruction::SLA(ArithmeticTarget::B)),
			0x21 => Some(Instruction::SLA(ArithmeticTarget::C)),
			0x22 => Some(Instruction::SLA(ArithmeticTarget::D)),
			0x23 => Some(Instruction::SLA(ArithmeticTarget::E)),
			0x24 => Some(Instruction::SLA(ArithmeticTarget::H)),
			0x25 => Some(Instruction::SLA(ArithmeticTarget::L)),
			0x26 => Some(Instruction::SLA(ArithmeticTarget::HL)),
			0x27 => Some(Instruction::SLA(ArithmeticTarget::A)),
			// SRA
			0x28 => Some(Instruction::SRA(ArithmeticTarget::B)),
			0x29 => Some(Instruction::SRA(ArithmeticTarget::C)),
			0x2A => Some(Instruction::SRA(ArithmeticTarget::D)),
			0x2B => Some(Instruction::SRA(ArithmeticTarget::E)),
			0x2C => Some(Instruction::SRA(ArithmeticTarget::H)),
			0x2D => Some(Instruction::SRA(ArithmeticTarget::L)),
			0x2E => Some(Instruction::SRA(ArithmeticTarget::HL)),
			0x2F => Some(Instruction::SRA(ArithmeticTarget::A)),
			// SWAP
			0x30 => Some(Instruction::SWAP(ArithmeticTarget::B)),
			0x31 => Some(Instruction::SWAP(ArithmeticTarget::C)),
			0x32 => Some(Instruction::SWAP(ArithmeticTarget::D)),
			0x33 => Some(Instruction::SWAP(ArithmeticTarget::E)),
			0x34 => Some(Instruction::SWAP(ArithmeticTarget::H)),
			0x35 => Some(Instruction::SWAP(ArithmeticTarget::L)),
			0x36 => Some(Instruction::SWAP(ArithmeticTarget::HL)),
			0x37 => Some(Instruction::SWAP(ArithmeticTarget::A)),
			// SRL
			0x38 => Some(Instruction::SRL(ArithmeticTarget::B)),
			0x39 => Some(Instruction::SRL(ArithmeticTarget::C)),
			0x3A => Some(Instruction::SRL(ArithmeticTarget::D)),
			0x3B => Some(Instruction::SRL(ArithmeticTarget::E)),
			0x3C => Some(Instruction::SRL(ArithmeticTarget::H)),
			0x3D => Some(Instruction::SRL(ArithmeticTarget::L)),
			0x3E => Some(Instruction::SRL(ArithmeticTarget::HL)),
			0x3F => Some(Instruction::SRL(ArithmeticTarget::A)),
			// BIT 0
			// TODO: there's probably a more concise way to set the val depending on opcode range. e.g.
			// 0x40..=0x4F => v = 0,
			// but there i wont' know which target it goes to, just the value.
			0x40 => Some(Instruction::BIT(0, ArithmeticTarget::B)),
			0x41 => Some(Instruction::BIT(0, ArithmeticTarget::C)),
			0x42 => Some(Instruction::BIT(0, ArithmeticTarget::D)),
			0x43 => Some(Instruction::BIT(0, ArithmeticTarget::E)),
			0x44 => Some(Instruction::BIT(0, ArithmeticTarget::H)),
			0x45 => Some(Instruction::BIT(0, ArithmeticTarget::L)),
			0x46 => Some(Instruction::BIT(0, ArithmeticTarget::HL)),
			0x47 => Some(Instruction::BIT(0, ArithmeticTarget::A)),
			// BIT 1
			0x48 => Some(Instruction::BIT(1, ArithmeticTarget::B)),
			0x49 => Some(Instruction::BIT(1, ArithmeticTarget::C)),
			0x4A => Some(Instruction::BIT(1, ArithmeticTarget::D)),
			0x4B => Some(Instruction::BIT(1, ArithmeticTarget::E)),
			0x4C => Some(Instruction::BIT(1, ArithmeticTarget::H)),
			0x4D => Some(Instruction::BIT(1, ArithmeticTarget::L)),
			0x4E => Some(Instruction::BIT(1, ArithmeticTarget::HL)),
			0x4F => Some(Instruction::BIT(1, ArithmeticTarget::A)),
			// BIT 2
			0x50 => Some(Instruction::BIT(2, ArithmeticTarget::B)),
			0x51 => Some(Instruction::BIT(2, ArithmeticTarget::C)),
			0x52 => Some(Instruction::BIT(2, ArithmeticTarget::D)),
			0x53 => Some(Instruction::BIT(2, ArithmeticTarget::E)),
			0x54 => Some(Instruction::BIT(2, ArithmeticTarget::H)),
			0x55 => Some(Instruction::BIT(2, ArithmeticTarget::L)),
			0x56 => Some(Instruction::BIT(2, ArithmeticTarget::HL)),
			0x57 => Some(Instruction::BIT(2, ArithmeticTarget::A)),
			// BIT 3
			0x58 => Some(Instruction::BIT(3, ArithmeticTarget::B)),
			0x59 => Some(Instruction::BIT(3, ArithmeticTarget::C)),
			0x5A => Some(Instruction::BIT(3, ArithmeticTarget::D)),
			0x5B => Some(Instruction::BIT(3, ArithmeticTarget::E)),
			0x5C => Some(Instruction::BIT(3, ArithmeticTarget::H)),
			0x5D => Some(Instruction::BIT(3, ArithmeticTarget::L)),
			0x5E => Some(Instruction::BIT(3, ArithmeticTarget::HL)),
			0x5F => Some(Instruction::BIT(3, ArithmeticTarget::A)),
			// BIT 4
			0x60 => Some(Instruction::BIT(4, ArithmeticTarget::B)),
			0x61 => Some(Instruction::BIT(4, ArithmeticTarget::C)),
			0x62 => Some(Instruction::BIT(4, ArithmeticTarget::D)),
			0x63 => Some(Instruction::BIT(4, ArithmeticTarget::E)),
			0x64 => Some(Instruction::BIT(4, ArithmeticTarget::H)),
			0x65 => Some(Instruction::BIT(4, ArithmeticTarget::L)),
			0x66 => Some(Instruction::BIT(4, ArithmeticTarget::HL)),
			0x67 => Some(Instruction::BIT(4, ArithmeticTarget::A)),
			// BIT 5
			0x68 => Some(Instruction::BIT(5, ArithmeticTarget::B)),
			0x69 => Some(Instruction::BIT(5, ArithmeticTarget::C)),
			0x6A => Some(Instruction::BIT(5, ArithmeticTarget::D)),
			0x6B => Some(Instruction::BIT(5, ArithmeticTarget::E)),
			0x6C => Some(Instruction::BIT(5, ArithmeticTarget::H)),
			0x6D => Some(Instruction::BIT(5, ArithmeticTarget::L)),
			0x6E => Some(Instruction::BIT(5, ArithmeticTarget::HL)),
			0x6F => Some(Instruction::BIT(5, ArithmeticTarget::A)),
			// BIT 6
			0x70 => Some(Instruction::BIT(6, ArithmeticTarget::B)),
			0x71 => Some(Instruction::BIT(6, ArithmeticTarget::C)),
			0x72 => Some(Instruction::BIT(6, ArithmeticTarget::D)),
			0x73 => Some(Instruction::BIT(6, ArithmeticTarget::E)),
			0x74 => Some(Instruction::BIT(6, ArithmeticTarget::H)),
			0x75 => Some(Instruction::BIT(6, ArithmeticTarget::L)),
			0x76 => Some(Instruction::BIT(6, ArithmeticTarget::HL)),
			0x77 => Some(Instruction::BIT(6, ArithmeticTarget::A)),
			// BIT 7
			0x78 => Some(Instruction::BIT(7, ArithmeticTarget::B)),
			0x79 => Some(Instruction::BIT(7, ArithmeticTarget::C)),
			0x7A => Some(Instruction::BIT(7, ArithmeticTarget::D)),
			0x7B => Some(Instruction::BIT(7, ArithmeticTarget::E)),
			0x7C => Some(Instruction::BIT(7, ArithmeticTarget::H)),
			0x7D => Some(Instruction::BIT(7, ArithmeticTarget::L)),
			0x7E => Some(Instruction::BIT(7, ArithmeticTarget::HL)),
			0x7F => Some(Instruction::BIT(7, ArithmeticTarget::A)),
			// RES 0
			0x80 => Some(Instruction::RESET(0, ArithmeticTarget::B)),
			0x81 => Some(Instruction::RESET(0, ArithmeticTarget::C)),
			0x82 => Some(Instruction::RESET(0, ArithmeticTarget::D)),
			0x83 => Some(Instruction::RESET(0, ArithmeticTarget::E)),
			0x84 => Some(Instruction::RESET(0, ArithmeticTarget::H)),
			0x85 => Some(Instruction::RESET(0, ArithmeticTarget::L)),
			0x86 => Some(Instruction::RESET(0, ArithmeticTarget::HL)),
			0x87 => Some(Instruction::RESET(0, ArithmeticTarget::A)),
			// RES 1
			0x88 => Some(Instruction::RESET(1, ArithmeticTarget::B)),
			0x89 => Some(Instruction::RESET(1, ArithmeticTarget::C)),
			0x8A => Some(Instruction::RESET(1, ArithmeticTarget::D)),
			0x8B => Some(Instruction::RESET(1, ArithmeticTarget::E)),
			0x8C => Some(Instruction::RESET(1, ArithmeticTarget::H)),
			0x8D => Some(Instruction::RESET(1, ArithmeticTarget::L)),
			0x8E => Some(Instruction::RESET(1, ArithmeticTarget::HL)),
			0x8F => Some(Instruction::RESET(1, ArithmeticTarget::A)),
			// RES 2
			0x90 => Some(Instruction::RESET(2, ArithmeticTarget::B)),
			0x91 => Some(Instruction::RESET(2, ArithmeticTarget::C)),
			0x92 => Some(Instruction::RESET(2, ArithmeticTarget::D)),
			0x93 => Some(Instruction::RESET(2, ArithmeticTarget::E)),
			0x94 => Some(Instruction::RESET(2, ArithmeticTarget::H)),
			0x95 => Some(Instruction::RESET(2, ArithmeticTarget::L)),
			0x96 => Some(Instruction::RESET(2, ArithmeticTarget::HL)),
			0x97 => Some(Instruction::RESET(2, ArithmeticTarget::A)),
			// RES 3
			0x98 => Some(Instruction::RESET(3, ArithmeticTarget::B)),
			0x99 => Some(Instruction::RESET(3, ArithmeticTarget::C)),
			0x9A => Some(Instruction::RESET(3, ArithmeticTarget::D)),
			0x9B => Some(Instruction::RESET(3, ArithmeticTarget::E)),
			0x9C => Some(Instruction::RESET(3, ArithmeticTarget::H)),
			0x9D => Some(Instruction::RESET(3, ArithmeticTarget::L)),
			0x9E => Some(Instruction::RESET(3, ArithmeticTarget::HL)),
			0x9F => Some(Instruction::RESET(3, ArithmeticTarget::A)),
			// RES 4
			0xA0 => Some(Instruction::RESET(4, ArithmeticTarget::B)),
			0xA1 => Some(Instruction::RESET(4, ArithmeticTarget::C)),
			0xA2 => Some(Instruction::RESET(4, ArithmeticTarget::D)),
			0xA3 => Some(Instruction::RESET(4, ArithmeticTarget::E)),
			0xA4 => Some(Instruction::RESET(4, ArithmeticTarget::H)),
			0xA5 => Some(Instruction::RESET(4, ArithmeticTarget::L)),
			0xA6 => Some(Instruction::RESET(4, ArithmeticTarget::HL)),
			0xA7 => Some(Instruction::RESET(4, ArithmeticTarget::A)),
			// RES 5
			0xA8 => Some(Instruction::RESET(5, ArithmeticTarget::B)),
			0xA9 => Some(Instruction::RESET(5, ArithmeticTarget::C)),
			0xAA => Some(Instruction::RESET(5, ArithmeticTarget::D)),
			0xAB => Some(Instruction::RESET(5, ArithmeticTarget::E)),
			0xAC => Some(Instruction::RESET(5, ArithmeticTarget::H)),
			0xAD => Some(Instruction::RESET(5, ArithmeticTarget::L)),
			0xAE => Some(Instruction::RESET(5, ArithmeticTarget::HL)),
			0xAF => Some(Instruction::RESET(5, ArithmeticTarget::A)),
			// RES 6
			0xB0 => Some(Instruction::RESET(6, ArithmeticTarget::B)),
			0xB1 => Some(Instruction::RESET(6, ArithmeticTarget::C)),
			0xB2 => Some(Instruction::RESET(6, ArithmeticTarget::D)),
			0xB3 => Some(Instruction::RESET(6, ArithmeticTarget::E)),
			0xB4 => Some(Instruction::RESET(6, ArithmeticTarget::H)),
			0xB5 => Some(Instruction::RESET(6, ArithmeticTarget::L)),
			0xB6 => Some(Instruction::RESET(6, ArithmeticTarget::HL)),
			0xB7 => Some(Instruction::RESET(6, ArithmeticTarget::A)),
			// RES 7
			0xB8 => Some(Instruction::RESET(7, ArithmeticTarget::B)),
			0xB9 => Some(Instruction::RESET(7, ArithmeticTarget::C)),
			0xBA => Some(Instruction::RESET(7, ArithmeticTarget::D)),
			0xBB => Some(Instruction::RESET(7, ArithmeticTarget::E)),
			0xBC => Some(Instruction::RESET(7, ArithmeticTarget::H)),
			0xBD => Some(Instruction::RESET(7, ArithmeticTarget::L)),
			0xBE => Some(Instruction::RESET(7, ArithmeticTarget::HL)),
			0xBF => Some(Instruction::RESET(7, ArithmeticTarget::A)),
			// SET 0
			0xC0 => Some(Instruction::SET(0, ArithmeticTarget::B)),
			0xC1 => Some(Instruction::SET(0, ArithmeticTarget::C)),
			0xC2 => Some(Instruction::SET(0, ArithmeticTarget::D)),
			0xC3 => Some(Instruction::SET(0, ArithmeticTarget::E)),
			0xC4 => Some(Instruction::SET(0, ArithmeticTarget::H)),
			0xC5 => Some(Instruction::SET(0, ArithmeticTarget::L)),
			0xC6 => Some(Instruction::SET(0, ArithmeticTarget::HL)),
			0xC7 => Some(Instruction::SET(0, ArithmeticTarget::A)),
			// SET 1
			0xC8 => Some(Instruction::SET(1, ArithmeticTarget::B)),
			0xC9 => Some(Instruction::SET(1, ArithmeticTarget::C)),
			0xCA => Some(Instruction::SET(1, ArithmeticTarget::D)),
			0xCB => Some(Instruction::SET(1, ArithmeticTarget::E)),
			0xCC => Some(Instruction::SET(1, ArithmeticTarget::H)),
			0xCD => Some(Instruction::SET(1, ArithmeticTarget::L)),
			0xCE => Some(Instruction::SET(1, ArithmeticTarget::HL)),
			0xCF => Some(Instruction::SET(1, ArithmeticTarget::A)),
			// SET 2
			0xD0 => Some(Instruction::SET(2, ArithmeticTarget::B)),
			0xD1 => Some(Instruction::SET(2, ArithmeticTarget::C)),
			0xD2 => Some(Instruction::SET(2, ArithmeticTarget::D)),
			0xD3 => Some(Instruction::SET(2, ArithmeticTarget::E)),
			0xD4 => Some(Instruction::SET(2, ArithmeticTarget::H)),
			0xD5 => Some(Instruction::SET(2, ArithmeticTarget::L)),
			0xD6 => Some(Instruction::SET(2, ArithmeticTarget::HL)),
			0xD7 => Some(Instruction::SET(2, ArithmeticTarget::A)),
			// SET 3
			0xD8 => Some(Instruction::SET(3, ArithmeticTarget::B)),
			0xD9 => Some(Instruction::SET(3, ArithmeticTarget::C)),
			0xDA => Some(Instruction::SET(3, ArithmeticTarget::D)),
			0xDB => Some(Instruction::SET(3, ArithmeticTarget::E)),
			0xDC => Some(Instruction::SET(3, ArithmeticTarget::H)),
			0xDD => Some(Instruction::SET(3, ArithmeticTarget::L)),
			0xDE => Some(Instruction::SET(3, ArithmeticTarget::HL)),
			0xDF => Some(Instruction::SET(3, ArithmeticTarget::A)),
			// SET 4
			0xE0 => Some(Instruction::SET(4, ArithmeticTarget::B)),
			0xE1 => Some(Instruction::SET(4, ArithmeticTarget::C)),
			0xE2 => Some(Instruction::SET(4, ArithmeticTarget::D)),
			0xE3 => Some(Instruction::SET(4, ArithmeticTarget::E)),
			0xE4 => Some(Instruction::SET(4, ArithmeticTarget::H)),
			0xE5 => Some(Instruction::SET(4, ArithmeticTarget::L)),
			0xE6 => Some(Instruction::SET(4, ArithmeticTarget::HL)),
			0xE7 => Some(Instruction::SET(4, ArithmeticTarget::A)),
			// SET 5
			0xE8 => Some(Instruction::SET(5, ArithmeticTarget::B)),
			0xE9 => Some(Instruction::SET(5, ArithmeticTarget::C)),
			0xEA => Some(Instruction::SET(5, ArithmeticTarget::D)),
			0xEB => Some(Instruction::SET(5, ArithmeticTarget::E)),
			0xEC => Some(Instruction::SET(5, ArithmeticTarget::H)),
			0xED => Some(Instruction::SET(5, ArithmeticTarget::L)),
			0xEE => Some(Instruction::SET(5, ArithmeticTarget::HL)),
			0xEF => Some(Instruction::SET(5, ArithmeticTarget::A)),
			// SET 6
			0xF0 => Some(Instruction::SET(6, ArithmeticTarget::B)),
			0xF1 => Some(Instruction::SET(6, ArithmeticTarget::C)),
			0xF2 => Some(Instruction::SET(6, ArithmeticTarget::D)),
			0xF3 => Some(Instruction::SET(6, ArithmeticTarget::E)),
			0xF4 => Some(Instruction::SET(6, ArithmeticTarget::H)),
			0xF5 => Some(Instruction::SET(6, ArithmeticTarget::L)),
			0xF6 => Some(Instruction::SET(6, ArithmeticTarget::HL)),
			0xF7 => Some(Instruction::SET(6, ArithmeticTarget::A)),
			// SET 7
			0xF8 => Some(Instruction::SET(7, ArithmeticTarget::B)),
			0xF9 => Some(Instruction::SET(7, ArithmeticTarget::C)),
			0xFA => Some(Instruction::SET(7, ArithmeticTarget::D)),
			0xFB => Some(Instruction::SET(7, ArithmeticTarget::E)),
			0xFC => Some(Instruction::SET(7, ArithmeticTarget::H)),
			0xFD => Some(Instruction::SET(7, ArithmeticTarget::L)),
			0xFE => Some(Instruction::SET(7, ArithmeticTarget::HL)),
			0xFF => Some(Instruction::SET(7, ArithmeticTarget::A)),
		}
	}
	fn from_byte_not_prefixed(byte: u8) -> Option<Instruction> {
		match byte {
			0x00 => Some(Instruction::NOP),
			0x01 => Some(Instruction::LD(LoadType::Word(
				Reg16Target::BC,
				Reg16Source::D16,
			))),
			0x02 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::BCI,
				Reg8Source::A,
			))),
			0x03 => Some(Instruction::INC16(Reg16Target::BC)),
			0x04 => Some(Instruction::INC(ArithmeticTarget::B)),
			0x05 => Some(Instruction::DEC(ArithmeticTarget::B)),
			0x06 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::D8,
			))),
			0x07 => Some(Instruction::RLCA),
			0x08 => Some(Instruction::LD(LoadType::IndirectFromSP)),
			0x09 => Some(Instruction::ADD16(Reg16Target::BC)),
			0x0A => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::BCI,
			))),
			0x0B => Some(Instruction::DEC16(Reg16Target::BC)),
			0x0C => Some(Instruction::INC(ArithmeticTarget::C)),
			0x0D => Some(Instruction::DEC(ArithmeticTarget::C)),
			0x0E => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::D8,
			))),
			0x0F => Some(Instruction::RRCA),
			0x10 => Some(Instruction::STOP),
			0x11 => Some(Instruction::LD(LoadType::Word(
				Reg16Target::DE,
				Reg16Source::D16,
			))),
			0x12 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::DEI,
				Reg8Source::A,
			))),
			0x13 => Some(Instruction::INC16(Reg16Target::DE)),
			0x14 => Some(Instruction::INC(ArithmeticTarget::D)),
			0x15 => Some(Instruction::DEC(ArithmeticTarget::D)),
			0x16 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::D8,
			))),
			0x17 => Some(Instruction::RLA),
			0x18 => Some(Instruction::JR(JumpTest::Always)),
			0x19 => Some(Instruction::ADD16(Reg16Target::DE)),
			0x1A => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::DEI,
			))),
			0x1B => Some(Instruction::DEC16(Reg16Target::DE)),
			0x1C => Some(Instruction::INC(ArithmeticTarget::E)),
			0x1D => Some(Instruction::DEC(ArithmeticTarget::E)),
			0x1E => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::D8,
			))),
			0x1F => Some(Instruction::RRA),
			0x20 => Some(Instruction::JR(JumpTest::NotZero)),
			0x21 => Some(Instruction::LD(LoadType::Word(
				Reg16Target::HL,
				Reg16Source::D16,
			))),
			0x22 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLINC,
				Reg8Source::A,
			))),
			0x23 => Some(Instruction::INC16(Reg16Target::HL)),
			0x24 => Some(Instruction::INC(ArithmeticTarget::H)),
			0x25 => Some(Instruction::DEC(ArithmeticTarget::H)),
			0x26 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::D8,
			))),
			0x27 => Some(Instruction::DAA),
			0x28 => Some(Instruction::JR(JumpTest::Zero)),
			0x29 => Some(Instruction::ADD16(Reg16Target::HL)),
			0x2A => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::HLINC,
			))),
			0x2B => Some(Instruction::DEC16(Reg16Target::HL)),
			0x2C => Some(Instruction::INC(ArithmeticTarget::L)),
			0x2D => Some(Instruction::DEC(ArithmeticTarget::L)),
			0x2E => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::D8,
			))),
			0x2F => Some(Instruction::CPL),
			0x30 => Some(Instruction::JR(JumpTest::NotCarry)),
			0x31 => Some(Instruction::LD(LoadType::Word(
				Reg16Target::SP,
				Reg16Source::D16,
			))),
			0x32 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLDEC,
				Reg8Source::A,
			))),
			0x33 => Some(Instruction::INC16(Reg16Target::SP)),
			0x34 => Some(Instruction::INC(ArithmeticTarget::HL)),
			0x35 => Some(Instruction::DEC(ArithmeticTarget::HL)),
			0x36 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLI,
				Reg8Source::D8,
			))),
			0x37 => Some(Instruction::SCF),
			0x38 => Some(Instruction::JR(JumpTest::Carry)),
			0x39 => Some(Instruction::ADD16(Reg16Target::SP)),
			0x3A => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::HLDEC,
			))),
			0x3B => Some(Instruction::DEC16(Reg16Target::SP)),
			0x3C => Some(Instruction::INC(ArithmeticTarget::A)),
			0x3D => Some(Instruction::DEC(ArithmeticTarget::A)),
			0x3E => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::D8,
			))),
			0x3F => Some(Instruction::CCF),
			0x40 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::B,
			))),
			0x41 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::C,
			))),
			0x42 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::D,
			))),
			0x43 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::E,
			))),
			0x44 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::H,
			))),
			0x45 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::L,
			))),
			0x46 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::HLI,
			))),
			0x47 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::B,
				Reg8Source::A,
			))),
			0x48 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::B,
			))),
			0x49 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::C,
			))),
			0x4A => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::D,
			))),
			0x4B => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::E,
			))),
			0x4C => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::H,
			))),
			0x4D => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::L,
			))),
			0x4E => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::HLI,
			))),
			0x4F => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::C,
				Reg8Source::A,
			))),
			0x50 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::B,
			))),
			0x51 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::C,
			))),
			0x52 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::D,
			))),
			0x53 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::E,
			))),
			0x54 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::H,
			))),
			0x55 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::L,
			))),
			0x56 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::HLI,
			))),
			0x57 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::D,
				Reg8Source::A,
			))),
			0x58 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::B,
			))),
			0x59 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::C,
			))),
			0x5A => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::D,
			))),
			0x5B => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::E,
			))),
			0x5C => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::H,
			))),
			0x5D => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::L,
			))),
			0x5E => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::HLI,
			))),
			0x5F => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::E,
				Reg8Source::A,
			))),
			0x60 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::B,
			))),
			0x61 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::C,
			))),
			0x62 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::D,
			))),
			0x63 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::E,
			))),
			0x64 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::H,
			))),
			0x65 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::L,
			))),
			0x66 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::HLI,
			))),
			0x67 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::H,
				Reg8Source::A,
			))),
			0x68 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::B,
			))),
			0x69 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::C,
			))),
			0x6A => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::D,
			))),
			0x6B => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::E,
			))),
			0x6C => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::H,
			))),
			0x6D => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::L,
			))),
			0x6E => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::HLI,
			))),
			0x6F => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::L,
				Reg8Source::A,
			))),
			0x70 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLI,
				Reg8Source::B,
			))),
			0x71 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLI,
				Reg8Source::C,
			))),
			0x72 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLI,
				Reg8Source::D,
			))),
			0x73 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLI,
				Reg8Source::E,
			))),
			0x74 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLI,
				Reg8Source::H,
			))),
			0x75 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLI,
				Reg8Source::L,
			))),
			0x76 => Some(Instruction::HALT),
			0x77 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::HLI,
				Reg8Source::A,
			))),
			0x78 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::B,
			))),
			0x79 => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::C,
			))),
			0x7A => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::D,
			))),
			0x7B => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::E,
			))),
			0x7C => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::H,
			))),
			0x7D => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::L,
			))),
			0x7E => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::HLI,
			))),
			0x7F => Some(Instruction::LD(LoadType::Byte(
				Reg8Target::A,
				Reg8Source::A,
			))),
			0x80 => Some(Instruction::ADD(ArithmeticTarget::B)),
			0x81 => Some(Instruction::ADD(ArithmeticTarget::C)),
			0x82 => Some(Instruction::ADD(ArithmeticTarget::D)),
			0x83 => Some(Instruction::ADD(ArithmeticTarget::E)),
			0x84 => Some(Instruction::ADD(ArithmeticTarget::H)),
			0x85 => Some(Instruction::ADD(ArithmeticTarget::L)),
			0x86 => Some(Instruction::ADD(ArithmeticTarget::HL)),
			0x87 => Some(Instruction::ADD(ArithmeticTarget::A)),
			0x88 => Some(Instruction::ADDC(ArithmeticTarget::B)),
			0x89 => Some(Instruction::ADDC(ArithmeticTarget::C)),
			0x8A => Some(Instruction::ADDC(ArithmeticTarget::D)),
			0x8B => Some(Instruction::ADDC(ArithmeticTarget::E)),
			0x8C => Some(Instruction::ADDC(ArithmeticTarget::H)),
			0x8D => Some(Instruction::ADDC(ArithmeticTarget::L)),
			0x8E => Some(Instruction::ADDC(ArithmeticTarget::HL)),
			0x8F => Some(Instruction::ADDC(ArithmeticTarget::A)),
			0x90 => Some(Instruction::SUB(ArithmeticTarget::B)),
			0x91 => Some(Instruction::SUB(ArithmeticTarget::C)),
			0x92 => Some(Instruction::SUB(ArithmeticTarget::D)),
			0x93 => Some(Instruction::SUB(ArithmeticTarget::E)),
			0x94 => Some(Instruction::SUB(ArithmeticTarget::H)),
			0x95 => Some(Instruction::SUB(ArithmeticTarget::L)),
			0x96 => Some(Instruction::SUB(ArithmeticTarget::HL)),
			0x97 => Some(Instruction::SUB(ArithmeticTarget::A)),
			0x98 => Some(Instruction::SUBC(ArithmeticTarget::B)),
			0x99 => Some(Instruction::SUBC(ArithmeticTarget::C)),
			0x9A => Some(Instruction::SUBC(ArithmeticTarget::D)),
			0x9B => Some(Instruction::SUBC(ArithmeticTarget::E)),
			0x9C => Some(Instruction::SUBC(ArithmeticTarget::H)),
			0x9D => Some(Instruction::SUBC(ArithmeticTarget::L)),
			0x9E => Some(Instruction::SUBC(ArithmeticTarget::HL)),
			0x9F => Some(Instruction::SUBC(ArithmeticTarget::A)),
			0xA0 => Some(Instruction::AND(ArithmeticTarget::B)),
			0xA1 => Some(Instruction::AND(ArithmeticTarget::C)),
			0xA2 => Some(Instruction::AND(ArithmeticTarget::D)),
			0xA3 => Some(Instruction::AND(ArithmeticTarget::E)),
			0xA4 => Some(Instruction::AND(ArithmeticTarget::H)),
			0xA5 => Some(Instruction::AND(ArithmeticTarget::L)),
			0xA6 => Some(Instruction::AND(ArithmeticTarget::HL)),
			0xA7 => Some(Instruction::AND(ArithmeticTarget::A)),
			0xA8 => Some(Instruction::XOR(ArithmeticTarget::B)),
			0xA9 => Some(Instruction::XOR(ArithmeticTarget::C)),
			0xAA => Some(Instruction::XOR(ArithmeticTarget::D)),
			0xAB => Some(Instruction::XOR(ArithmeticTarget::E)),
			0xAC => Some(Instruction::XOR(ArithmeticTarget::H)),
			0xAD => Some(Instruction::XOR(ArithmeticTarget::L)),
			0xAE => Some(Instruction::XOR(ArithmeticTarget::HL)),
			0xAF => Some(Instruction::XOR(ArithmeticTarget::A)),
			0xB0 => Some(Instruction::OR(ArithmeticTarget::B)),
			0xB1 => Some(Instruction::OR(ArithmeticTarget::C)),
			0xB2 => Some(Instruction::OR(ArithmeticTarget::D)),
			0xB3 => Some(Instruction::OR(ArithmeticTarget::E)),
			0xB4 => Some(Instruction::OR(ArithmeticTarget::H)),
			0xB5 => Some(Instruction::OR(ArithmeticTarget::L)),
			0xB6 => Some(Instruction::OR(ArithmeticTarget::HL)),
			0xB7 => Some(Instruction::OR(ArithmeticTarget::A)),
			0xB8 => Some(Instruction::CMP(ArithmeticTarget::B)),
			0xB9 => Some(Instruction::CMP(ArithmeticTarget::C)),
			0xBA => Some(Instruction::CMP(ArithmeticTarget::D)),
			0xBB => Some(Instruction::CMP(ArithmeticTarget::E)),
			0xBC => Some(Instruction::CMP(ArithmeticTarget::H)),
			0xBD => Some(Instruction::CMP(ArithmeticTarget::L)),
			0xBE => Some(Instruction::CMP(ArithmeticTarget::HL)),
			0xBF => Some(Instruction::CMP(ArithmeticTarget::A)),
			0xC0 => Some(Instruction::RET(JumpTest::NotZero)),
			0xC1 => Some(Instruction::POP(StackTarget::BC)),
			0xC2 => Some(Instruction::JP(JumpTest::NotZero)),
			0xC3 => Some(Instruction::JP(JumpTest::Always)),
			0xC4 => Some(Instruction::CALL(JumpTest::NotZero)),
			0xC5 => Some(Instruction::PUSH(StackTarget::BC)),
			0xC6 => Some(Instruction::ADD(ArithmeticTarget::D8)),
			0xC7 => Some(Instruction::RST(0x00)),
			0xC8 => Some(Instruction::RET(JumpTest::Zero)),
			0xC9 => Some(Instruction::RET(JumpTest::Always)),
			0xCA => Some(Instruction::JP(JumpTest::Zero)),
			0xCB => panic!("Don't think prefix should ever be fed here?"),
			0xCC => Some(Instruction::CALL(JumpTest::Zero)),
			0xCD => Some(Instruction::CALL(JumpTest::Always)),
			0xCE => Some(Instruction::ADDC(ArithmeticTarget::D8)),
			0xCF => Some(Instruction::RST(0x08)),
			0xD0 => Some(Instruction::RET(JumpTest::NotCarry)),
			0xD1 => Some(Instruction::POP(StackTarget::DE)),
			0xD2 => Some(Instruction::JP(JumpTest::NotCarry)),
			0xD3 => panic!("Not an op"),
			0xD4 => Some(Instruction::CALL(JumpTest::NotCarry)),
			0xD5 => Some(Instruction::PUSH(StackTarget::DE)),
			0xD6 => Some(Instruction::SUB(ArithmeticTarget::D8)),
			0xD7 => Some(Instruction::RST(0x10)),
			0xD8 => Some(Instruction::RET(JumpTest::Carry)),
			0xD9 => Some(Instruction::RETI),
			0xDA => Some(Instruction::JP(JumpTest::Carry)),
			0xDB => panic!("Not an op"),
			0xDC => Some(Instruction::CALL(JumpTest::Carry)),
			0xDD => panic!("Not an op"),
			0xDE => Some(Instruction::SUBC(ArithmeticTarget::D8)),
			0xDF => Some(Instruction::RST(0x18)),
			// 0xE0 => Some(Instruction::LDH(0x18)),
			_ => {
				unimplemented!("Unimplemented opcode: {}", byte)
			}
		}
	}
}
pub(crate) enum ArithmeticTarget {
	A,
	B,
	C,
	D,
	E,
	H,
	L,
	HL,
	D8,
}
pub(crate) enum JumpTest {
	NotZero,
	Zero,
	NotCarry,
	Carry,
	Always,
}
pub(crate) enum Reg8Target {
	A,
	B,
	C,
	D,
	E,
	H,
	L,
	BCI,
	DEI,
	HLI,
	HLINC,
	HLDEC,
}
pub(crate) enum Reg8Source {
	A,
	B,
	C,
	D,
	E,
	H,
	L,
	D8,
	BCI,
	DEI,
	HLI,
	HLINC,
	HLDEC,
}
pub(crate) enum Reg16Target {
	BC,
	DE,
	HL,
	SP,
}
pub(crate) enum Reg16Source {
	D16,
}
pub(crate) enum LoadType {
	Byte(Reg8Target, Reg8Source),
	Word(Reg16Target, Reg16Source),
	IndirectFromSP, // only opcode to store SP to arbitrary addr
}

pub(crate) enum StackTarget {
	AF,
	BC,
	DE,
	HL,
}
